### ISSUE TITLE
creating too many semaphores

### ISSUE THREAD

**Issue by christiancadieux** [bluele/redis-semaphore#1]
when trying this code in multiple processes and using one more process to count the number of
semaphores, I noticed that the number would easily double (from 4 to 8) , even if all the processes
request 4 semaphores. This happens when I interrupt and restart the programs often. Maybe this is only a problem with gevent, not sure:

TEST PROGRAM:
# !/usr/bin/python

import gevent.monkey
gevent.monkey.patch_all()
import signal
import sys
import redis
import redis_lock
import time
import os
from redis_semaphore import Semaphore
from threading import Thread
import urllib2
import time
exiting = False
def signal_handler(signal, frame):
  global exiting
  exiting = True
signal.signal(signal.SIGINT, signal_handler)

rd = redis.StrictRedis()
semaphore = Semaphore(rd, count=4, namespace='cairo')
def task(i):
    gevent.sleep(1)
    with semaphore:
      print "Starting task", i
      gevent.sleep(0.5)

def test1():
    global exiting
    cnt = 0
    while cnt < 1000:
       jobs = [gevent.spawn(task, i) for i in range(1,10)]
       gevent.joinall(jobs, timeout=200)
       gevent.sleep(2)
       cnt+= 1
       if exiting:
         print "Exiting!"
         break
test1()

COUNTER:
# !/usr/bin/python

import gevent.monkey
gevent.monkey.patch_all()
import redis
import redis_lock
import time
import os
from redis_semaphore import Semaphore
from threading import Thread
import urllib2
import time
rd = redis.StrictRedis()
semaphore = Semaphore(rd,4, namespace='cairo')
while True:
   print semaphore.available_count
   gevent.sleep(0.5)

I noticed that when I change the **init** methods, to use _exists_or_init instead of _init, the
problem stops:

class Semaphore(object):
    exists_val = 'ok'
    def **init**(self, client, count, namespace=None, stale_client_timeout=None):
        self.client = client or StrictRedis()
        if count < 1:
            raise ValueError("Parameter 'count' must be larger than 1")
        self.count = count
        self.namespace = namespace if namespace else 'SEMAPHORE'
        self.stale_client_timeout = stale_client_timeout
        self.is_use_local_time = False
        #self._init()
        self._exists_or_init()
        self._local_tokens = list()

**Comment by sibson** [comment]
dup of #2 or vice-versa

**Comment by bluele** [comment]
Fix this issue at #3
