### ISSUE TITLE
redis-semaphore is not a distributed semaphore

### ISSUE THREAD

**Issue by suligap** [bluele/redis-semaphore#2]
README says:

> A distributed semaphore and mutex built on Redis.

This isn't true. Creating the "same" semaphore `semaphore = Semaphore(Redis(), count=1, namespace='spam')` in two different threads/processes does not result in `with semaphore: ...` having desired effect (both processes will execute the `with` block together).

It only works as intended when you create a global semaphore shared by two threads like in the [example](https://github.com/bluele/redis-semaphore/blob/f7510c3d1ee551b1f7a7af12b9ce7c52efefe995/examples/semaphore.py). Needless to say redis is not required to achieve the result redis-semaphore achieves.

**Comment by omerra** [comment]
suligap is right. This is not a distributed semaphore.
Everytime Init is called on this class, it resets the semaphore. It can only work between threads if created once. It is definitely not for multi-processes.
It could easily be changed to be distributed, and it seems like some of the code has been done to do it, but currently it is not

**Comment by sibson** [comment]
changing `_init` to `_exists_or_init` in `__init__` might be sufficient to fix the problem.
